[package]
name = "bevy_server_persistence"
version = "0.1.0"
edition = "2021"

[dependencies]
redis = { version = "0.24", features = ["connection-manager", "ahash", "keep-alive", "async-std-comp"] }
bevy = "0.12"
url = "2.5"
uuid = "1.6"
async-std = "1.12"
anyhow = "1.0"